export default [
  {
    title: 'Project Manager Senior',
    slug: 'project-manager-senior',
    author: 'Dario Miñones',
    tags: ['posiciones'],
    date: '2018-01-01 15:26 PDT',
    body:
      '\n## Estamos buscando\n\n* Nombre del Rol: Project Manager\n* Sector: Desarrollo de Software\n* Nivel: Senior\n* Reporta a: Director General\n* Mail de Contacto: rrhh@cactus.ws\n\n## Que rol buscamos?\n\nProject Manager, de un nivel senior.\nAl menos 5 años de experiencia manejando proyectos de desarrollo de software.\n\nSignifica que vas a tener que definir tareas, estimar esfuerzos y organizarlas en proyectos;\narmar múltiples equipos y liderarlos; necesitamos de tu creatividad en la resolución de problemas; que puedas tomar decisiones en un ambiente con prioridades cambiantes; que puedas llevar una excelente relación con clientes, superiores, pares y equipo y que tengas capacidad de negociación.\n\nPara esto es importante que seas un buen comunicador, disfrutes de trabajar en equipo, y puedas manejar el trabajo bajo presión. \n\n## Donde estarías trabajando?\n\nEn una empresa de desarrollo de software a medida, donde hacemos apps, sitios y sistemas para grandes empresas como Bayer, Turner y Banco Galicia, y para Start Ups. Nuestro foco está puesto principalmente en el uso de tecnologías modernas como React, Angular y NodeJS, buscando siempre estar a la vanguardia tecnológica.\n\nSomos una empresa certificada ISO 9001, encuadrada dentro de la Ley de Software y donde utilizamos metodologías ágiles y de mejora continua. Esto es parte de nuestras ganas de hacer las cosas bien y superarnos cada día.\n\nCactus tiene una misión que es la de contribuir significativamente a los objetivos de negocio de sus clientes, mediante la creación de soluciones de software, que posibilite a las marcas vincularse de manera profunda y efectiva con sus consumidores así como resolver problemáticas internas de negocio.\n\n## Lo de adentro nos importa.\n\nEs necesario que seas buena persona, que seas super profesional, pero nunca te olvides de tu parte humana; seas responsable y tengas proactividad en la mejora continua.\n\n## Cactus tiene su actitud.\n\nLa creatividad e innovación es el eje principal que aplicamos a todo.\nNos divertimos y somos profesionales.\nNos gusta combinar momentos de distensión con la adrenalina de la presión de los proyectos.\nSomos internacionales, pero morimos por un choripan.\nHacemos deportes, tenemos hobbies y la pasamos bien. \n\n## Más que un plus.\n\nEstudiaste o estás en curso de la carrera de administración de empresas, ingeniería en sistemas / industrial, o experiencia profesional equivalente demostrable?\nTenés experiencia previa de al menos 5 año en un rol similar?\nManejas Trello, Slack y Ganttic?\nTu nivel de inglés es avanzado (oral y escrito)?\n',
  },
];
